name: release
on:
  push:
    branches:
      - main

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v3.0.0
        with:
          node-version: 14.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.2.1
        with:
          version: 6

      - run: pnpm install
      - run: pnpm run build

    # - name: publish
    #   uses: actions/setup-node@v1
    #     with:
    #       node-version: 14
    #       registry-url: https://registry.npmjs.org/
    #   - run: npm publish
    #     env:
    #       NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
